const data = [
	{
		id: 1,
		name: "DevOps",
		instructor:"mahiraj jadeja",
		university:"charusat university",
		info: "This course provides an overview of DevOps principles and practices, with a focus on how they can be applied in agile software development teams. Students will learn how to use popular tools and techniques for continuous integration, continuous delivery, and automated testing.",
		image: "https://codehelp-apis.vercel.app/get-top-courses/Development/Devops%20for%20Agile%20Teams.png",
		price: "35,758",
	},
	{
		id: 2,
		name: "Marketing",
		instructor:"meet patel",
		university:"charusat university",
		info: `This course provides an overview of marketing principles and practices, including market research, segmentation, targeting, and positioning. Students will learn how to create effective marketing plans and campaigns, using both traditional and digital marketing techniques.`,
		image: "https://codehelp-apis.vercel.app/get-top-courses/Business/Introduction%20To%20Marketing.png",
		price: "82,560",
	},
	{
		id: 3,
		name: "Design",
		instructor:"vansh patel",
		university:"charusat university",
		info: "This course covers the basic principles of graphic design, including typography, color theory, layout design, and image manipulation. Students will learn how to use industry-standard design software to create effective visual designs for print and digital media.",
		image: "https://codehelp-apis.vercel.app/get-top-courses/Design/Graphic%20Design%20Fundamentals.png",
		price: "29,695",
	},
	{
		id: 4,
		name: "Photography",
		instructor:"krish patel",
		university:"charusat university",
		info: "This course covers the fundamentals of travel photography, including composition, lighting, and storytelling. Students will learn how to use a range of camera equipment and editing software to capture and share their travel experiences.",
		image: "https://codehelp-apis.vercel.app/get-top-courses/Lifestyle/Travel%20Photography.png",
		price: "31,095",
	},
	{
		id: 5,
		name: "Fitness",
		instructor:"raj patel",
		university:"charusat university",
		info: "This course covers the fundamentals of fitness, including exercise principles, workout planning, and nutrition. Students will learn how to build strength, endurance, and flexibility, and how to create a healthy and sustainable lifestyle.",
		image:  "https://codehelp-apis.vercel.app/get-top-courses/Lifestyle/Fitness%20For%20Life.png",
		price: "78,595",
	},
	{
		id: 6,
		name: "Marketing",
		instructor:"anand parmar",
		university:"charusat university",
		info: `This course provides an overview of marketing principles and practices, including market research, segmentation, targeting, and positioning. Students will learn how to create effective marketing plans and campaigns, using both traditional and digital marketing techniques.`,
		image: "https://codehelp-apis.vercel.app/get-top-courses/Business/Introduction%20To%20Marketing.png",
		price: "82,560",
	},
	{
		id: 7,
		name: "Marketing",
		instructor:"vishal patel",
		university:"charusat university",
		info: `This course provides an overview of marketing principles and practices, including market research, segmentation, targeting, and positioning. Students will learn how to create effective marketing plans and campaigns, using both traditional and digital marketing techniques.`,
		image: "https://codehelp-apis.vercel.app/get-top-courses/Business/Introduction%20To%20Marketing.png",
		price: "82,560",
	},
	{
		id: 8,
		name: "Marketing",
		instructor:"vishal parmar",
		university:"charusat university",
		info: `This course provides an overview of marketing principles and practices, including market research, segmentation, targeting, and positioning. Students will learn how to create effective marketing plans and campaigns, using both traditional and digital marketing techniques.`,
		image: "https://codehelp-apis.vercel.app/get-top-courses/Business/Introduction%20To%20Marketing.png",
		price: "82,560",
	},
	
];

export default data;
